# Generated by Django 4.1.6 on 2023-02-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ufc', '0003_peopleturnir_socialmedia_trainer_turnir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ufc.turnir')),
            ],
            options={
                'verbose_name': 'Прошедший сбор',
                'verbose_name_plural': 'Прошедшие сборы',
            },
        ),
        migrations.CreateModel(
            name='FutureFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photoFutureFees/%Y/%m/%d/', verbose_name='')),
                ('sportman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ufc.sportman')),
                ('turnir', models.ManyToManyField(to='app_ufc.turnir', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Будущий сбор',
                'verbose_name_plural': 'Будущие сборы',
            },
        ),
    ]
