# Generated by Django 4.1.6 on 2023-02-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ufc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(upload_to='info/%y/%m/%d/', verbose_name='Фотки о предстоящих сборах'),
        ),
    ]
