# Generated by Django 4.1.6 on 2023-02-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ufc', '0003_peopleturnir_socialmedia_trainer_turnir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleturnir',
            name='name',
            field=models.CharField(default=123, max_length=100, verbose_name='Имя соперника: '),
            preserve_default=False,
        ),
    ]
