# Generated by Django 4.1.6 on 2023-02-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ufc', '0004_peopleturnir_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleturnir',
            old_name='name',
            new_name='anamy',
        ),
    ]
