# Generated by Django 4.1.6 on 2023-02-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ufc', '0005_rename_name_peopleturnir_anamy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleturnir',
            name='sportsmen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ufc.sportman', verbose_name='Боец'),
        ),
    ]
